In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
df1 = pd.read_excel('/content/drive/MyDrive/data/아파트 매매가격지수.xlsx의 사본')

In [ ]:
import requests

url = 'https://ecos.bok.or.kr/api/StatisticSearch/21SC44F70ZNCSG2AMIWU/json/kr/1/100/722Y001/D/20210101/20230331'
response = requests.get(url)
result = response.json()
list_total_count=(int)(result['StatisticSearch']['list_total_count'])
list_count=(int)(list_total_count/100) + 1


rows=[]
for i in range(0,list_count):
    start = str(i * 100 + 1)
    end = str((i + 1) * 100)

    url = 'https://ecos.bok.or.kr/api/StatisticSearch/21SC44F70ZNCSG2AMIWU/json/kr/' \
            + start + '/' + end + '/722Y001/D/20210101/20230331'
    response = requests.get(url)
    result = response.json()
    rows = rows + result['StatisticSearch']['row']

df2 =pd.DataFrame(rows)
df2

,STAT_CODE,STAT_NAME,ITEM_CODE1,ITEM_NAME1,ITEM_CODE2,ITEM_NAME2,ITEM_CODE3,ITEM_NAME3,ITEM_CODE4,ITEM_NAME4,UNIT_NAME,TIME,DATA_VALUE
0,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0108000,신성장·일자리지원 프로그램대출금리,None,None,None,None,None,None,연%,20210101,0.25
1,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0111000,영세자영업자지원 프로그램대출금리,None,None,None,None,None,None,연%,20210101,0.25
2,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0112000,지방중소기업지원 프로그램대출금리,None,None,None,None,None,None,연%,20210101,0.25
3,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0113000,설비투자지원 프로그램대출금리,None,None,None,None,None,None,연%,20210101,0.25
4,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,None,None,None,None,None,None,연%,20210101,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7375,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0113000,설비투자지원 프로그램대출금리,None,None,None,None,None,None,연%,20230331,2
7376,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0105000,자금조정 예금금리,None,None,None,None,None,None,연%,20230331,2.5
7377,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0104000,자금조정 대출금리,None,None,None,None,None,None,연%,20230331,4.5
7378,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0102000,정부대출금금리,None,None,None,None,None,None,연%,20230331,3.544
7379,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0107000,무역금융지원 프로그램대출금리,None,None,None,None,None,None,연%,20230331,2

In [ ]:
df1=df2[['ITEM_NAME1','TIME','DATA_VALUE']]
df1['date']=pd.to_datetime((df1['TIME'].str[:4] + '-' + df1['TIME'].str[4:6] + '-' + df1['TIME'].str[6:8]))
df1=df1.astype({'DATA_VALUE':'float'})
df1=df1.drop_duplicates()
df1

<ipython-input-11-04544c244a20>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['date']=pd.to_datetime((df1['TIME'].str[:4] + '-' + df1['TIME'].str[4:6] + '-' + df1['TIME'].str[6:8]))

              ITEM_NAME1      TIME  DATA_VALUE       date
0     신성장·일자리지원 프로그램대출금리  20210101       0.250 2021-01-01
1      영세자영업자지원 프로그램대출금리  20210101       0.250 2021-01-01
2      지방중소기업지원 프로그램대출금리  20210101       0.250 2021-01-01
3        설비투자지원 프로그램대출금리  20210101       0.250 2021-01-01
4              한국은행 기준금리  20210101       0.500 2021-01-01
...                  ...       ...         ...        ...
7375     설비투자지원 프로그램대출금리  20230331       2.000 2023-03-31
7376           자금조정 예금금리  20230331       2.500 2023-03-31
7377           자금조정 대출금리  20230331       4.500 2023-03-31
7378             정부대출금금리  20230331       3.544 2023-03-31
7379     무역금융지원 프로그램대출금리  20230331       2.000 2023-03-31

[7380 rows x 4 columns]

In [ ]:
import yfinance as yf
from datetime import datetime

enddate=datetime.now().strftime('%Y-%m-%d')
kospi=yf.download('^KS11', '2021-01-01', '2023-03-31', auto_adjust=True)
kospi

[*********************100%***********************]  1 of 1 completed

                   Open         High          Low        Close   Volume
Date
2021-01-04  2874.500000  2946.540039  2869.110107  2944.449951  1026500
2021-01-05  2943.669922  2990.570068  2921.840088  2990.570068  1519900
2021-01-06  2993.340088  3027.159912  2961.370117  2968.209961  1793400
2021-01-07  2980.750000  3055.280029  2980.750000  3031.679932  1524700
2021-01-08  3040.110107  3161.110107  3040.110107  3152.179932  1297900
...                 ...          ...          ...          ...      ...
2023-03-24  2421.270020  2423.760010  2399.489990  2414.959961   470100
2023-03-27  2423.939941  2423.939941  2395.969971  2409.219971   472200
2023-03-28  2418.689941  2434.939941  2415.340088  2434.939941   523500
2023-03-29  2432.629883  2443.949951  2428.610107  2443.919922   496600
2023-03-30  2452.969971  2462.699951  2439.429932  2453.159912   621300

[553 rows x 5 columns]